generate_change_requests:
  description: >
    Analise as notas de reunião (transcrição e highlights) e, com base na especificação funcional atual, identifique e gere change requests conforme o padrão do projeto.
  expected_output: >
    Arquivos markdown de change request, um para cada alteração identificada, nomeados pelo respectivo ID, conforme exemplos em /knowledge/samples/CRs_samples, salvos em /outputs/change_requests.
  agent: requirements_analyst_1

update_spec_and_changelog:
  description: >
    Analise os change requests gerados e a especificação funcional atual, identifique os pontos da especificação que devem ser atualizados e gere sugestões de alteração. Gere também um changelog conforme o padrão do projeto.
  expected_output: >
    Arquivo markdown com a lista de alterações sugeridas na especificação funcional, salvo em /outputs/. Arquivo de changelog em markdown conforme exemplos em /knowledge/samples/CL_samples, salvo em /outputs/.
  agent: requirements_analyst_2
